/* eslint-disable @next/next/no-html-link-for-pages */
const bookPackages = [
  { name:"E-book", up150:"R$ 329,90", up300:"R$ 349,90", over300:"Sob análise", items:["Diagramação digital","Capa profissional","ISBN digital","Ficha catalográfica (CIP)","QR Code e conselho editorial","Arquivo final em PDF"] },
  { name:"Autor Independente Essencial", up150:"R$ 359,90", up300:"R$ 389,90", over300:"R$ 429,90", items:["Diagramação profissional","2 propostas de capa","ISBN digital ou impresso","Ficha catalográfica (CIP)","QR Code e conselho editorial","Arquivo PDF para impressão"] },
  { name:"Autor Independente Completo", up150:"R$ 559,90", up300:"R$ 589,90", over300:"R$ 629,90", items:["Tudo do Pacote Essencial","Revisão ortográfica e gramatical","Arquivo para Amazon Kindle (KDP)","Ajustes finais antes da publicação"] },
];

const chapterPackages = [
  { name:"Publicação Simples", price:"R$ 197,90", description:"Para autores com o capítulo pronto para publicação.", items:["Publicação em até 8 dias úteis","Certificado de publicação e carta de aceite","ISBN da coletânea","Ficha catalográfica e conselho editorial","Perfil público do capítulo"] },
  { name:"Publicação com Revisão", price:"R$ 239,90", description:"Publicação com preparação textual e acadêmica.", items:["Tudo do pacote simples","Correção ortográfica e gramatical","Normalização ABNT como cortesia","Conferência editorial antes da publicação"] },
];

export default function PublicationPage(){
  return <main className="publication-page">
    <header className="site-header publication-header"><a className="brand brand-image" href="/"><img src="/worges-logo.png" alt="Worges Editoração"/></a><nav><a href="#livros">Livros</a><a href="#capitulos">Capítulos</a><a href="#academico">Autor Acadêmico</a><a href="#comparacao">Comparação</a></nav><a className="header-cta" href="/checkout">Contratar <span>↗</span></a></header>

    <section className="publication-hero"><p className="eyebrow">PACOTES E VALORES</p><h1>Escolha com clareza.<br/><em>Publique com segurança.</em></h1><p>Consulte todos os itens e preços antes de contratar. Nenhum cadastro é necessário para visualizar os valores.</p><div className="hero-actions"><a className="button primary" href="#comparacao">Comparar pacotes →</a><a className="button secondary" href="#capitulos">Publicar capítulo →</a></div></section>

    <section className="package-section" id="livros"><div className="package-heading"><div><p className="eyebrow">PUBLICAÇÃO DE LIVROS</p><h2>Pacotes por quantidade de páginas</h2></div><p>Na contratação, o sistema identifica automaticamente os registros incluídos no pacote. Quando houver DOI, o número será gerado sem preenchimento manual.</p></div><div className="package-cards">{bookPackages.map((pkg,index)=><article className={`package-card ${index===1?"featured":""}`} key={pkg.name}><span>0{index+1}</span><h3>{pkg.name}</h3><div className="package-prices"><p><small>Até 150 páginas</small><strong>{pkg.up150}</strong></p><p><small>Até 300 páginas</small><strong>{pkg.up300}</strong></p><p><small>Acima de 300 páginas</small><strong>{pkg.over300}</strong></p></div><ul>{pkg.items.map(item=><li key={item}>✓ {item}</li>)}</ul><a href={`/checkout?tipo=livro&pacote=${encodeURIComponent(pkg.name)}`}>Contratar este pacote →</a></article>)}</div></section>

    <section className="package-section chapter-packages" id="capitulos"><div className="package-heading"><div><p className="eyebrow">PUBLICAÇÃO DE CAPÍTULOS</p><h2>Escolha a coletânea e envie seu Word</h2></div><p>O autor seleciona a temática da coletânea, escolhe o pacote e anexa o capítulo em Word. A entrega inclui certificado, carta de aceite, ISBN da coletânea, ficha do livro e conselho editorial.</p></div><div className="chapter-package-grid">{chapterPackages.map((pkg,index)=><article className="chapter-package-card" key={pkg.name}><span>{index===0?"ESSENCIAL":"RECOMENDADO"}</span><h3>{pkg.name}</h3><strong>{pkg.price}</strong><p>{pkg.description}</p><ul>{pkg.items.map(item=><li key={item}>✓ {item}</li>)}</ul><a className="button primary" href={`/checkout?tipo=capitulo&pacote=${encodeURIComponent(pkg.name)}`}>Publicar meu capítulo →</a></article>)}<aside className="template-card"><p className="eyebrow">TEMPLATE GRATUITO</p><h3>Prepare seu capítulo no padrão editorial</h3><p>Baixe o arquivo editável com estrutura de título, autores, resumo, abstract, introdução, revisão de literatura, metodologia, resultados, considerações finais e referências.</p><a className="button secondary" href="/template-capitulo-worges.docx" download>Baixar template em Word ↓</a></aside></div></section>

    <section className="package-section academic-package" id="academico"><div><p className="eyebrow">AUTOR ACADÊMICO</p><h2>Combo Autor Acadêmico</h2><p>Ideal para TCC, dissertação, tese ou livro acadêmico com publicação editorial completa.</p><strong>R$ 629,90 <small>até 300 páginas</small></strong></div><ul><li>✓ Diagramação profissional e normalização ABNT</li><li>✓ Revisão ortográfica e gramatical</li><li>✓ Registro DOI e ISBN</li><li>✓ Ficha catalográfica (CIP), QR Code e conselho editorial</li><li>✓ Arquivo Kindle para Amazon KDP</li></ul><a className="button primary" href="/checkout?tipo=livro&pacote=Autor%20Acadêmico">Contratar pacote →</a></section>

    <section className="package-section comparison" id="comparacao"><div className="package-heading"><div><p className="eyebrow">COMPARAÇÃO</p><h2>Veja o que cada pacote possui</h2></div><p>Os valores ficam visíveis para todos. O formulário aparece somente quando o autor decide contratar.</p></div><div className="comparison-table"><table><thead><tr><th>Item</th><th>E-book</th><th>Essencial</th><th>Completo</th><th>Acadêmico</th><th>Capítulo</th></tr></thead><tbody><tr><td>Diagramação</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>ISBN</td><td>Digital</td><td>Digital ou impresso</td><td>Digital ou impresso</td><td>✓</td><td>Da coletânea</td></tr><tr><td>Ficha e conselho editorial</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Revisão</td><td>—</td><td>—</td><td>✓</td><td>✓</td><td>Pacote de R$ 239,90</td></tr><tr><td>DOI automático</td><td>Quando contratado</td><td>Quando incluído</td><td>Quando incluído</td><td>✓</td><td>Quando incluído</td></tr><tr><td>Download público</td><td colSpan={5}>Somente quando o autor autorizar durante a contratação</td></tr></tbody></table></div></section>

    <section className="publication-note"><strong>Publicação e privacidade</strong><p>A página pública da obra é criada automaticamente. O arquivo para download só aparece quando o autor marca essa autorização na contratação; caso contrário, apenas o perfil e as informações bibliográficas ficam visíveis.</p></section>
  </main>
}
